name: Setup
description: Perform standard setup and install dependencies using pnpm.
inputs:
  node-version:
    description: The version of Node.js to install
    required: false
  deno-version:
    description: The version of Deno to install
    required: false
  bun-version:
    description: The version of Bun to install
    required: false

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
    - name: Install node
      uses: actions/setup-node@v4
      if: ${{ inputs.node-version != '' }}
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}
    - name: Install deno
      uses: denoland/setup-deno@v2
      if: ${{ inputs.deno-version != '' }}
      with:
        deno-version: ${{ inputs.deno-version }}
    - name: Install bun
      uses: oven-sh/setup-bun@v2
      if: ${{ inputs.bun-version != '' }}
      with:
        bun-version: ${{ inputs.bun-version }}
    - name: Install dependencies
      shell: bash
      run: pnpm install
