import { defineConfig } from "tsdown"

export default defineConfig({
  entry: ["src/**/*.ts"],
  unbundle: true,
  format: "esm",
  // Declaration files (.d.ts) are generated by tsc in the root build step.
  // tsdown handles only JS transpilation.
  dts: false,
  // Output .js (not .mjs) since all packages use "type": "module"
  fixedExtension: false,
  sourcemap: true,
  // Do not clean dist/ -- tsc populates .d.ts files before tsdown runs
  clean: false
})
