export interface MemberRenameRule {
  readonly id: string;
  readonly object: string;
  readonly toObject?: string;
  readonly from: string;
  readonly to: string;
}

// Keep this as the single source of truth for deterministic member renames.
export const MEMBER_RENAME_RULES: ReadonlyArray<MemberRenameRule> = [
  { id: "effect-catchAll", object: "Effect", from: "catchAll", to: "catch" },
  {
    id: "effect-catchAllCause",
    object: "Effect",
    from: "catchAllCause",
    to: "catchCause",
  },
  {
    id: "effect-catchAllDefect",
    object: "Effect",
    from: "catchAllDefect",
    to: "catchDefect",
  },
  {
    id: "effect-catchSomeCause",
    object: "Effect",
    from: "catchSomeCause",
    to: "catchCauseFilter",
  },
  { id: "effect-fork", object: "Effect", from: "fork", to: "forkChild" },
  {
    id: "effect-forkDaemon",
    object: "Effect",
    from: "forkDaemon",
    to: "forkDetach",
  },
  { id: "scope-extend", object: "Scope", from: "extend", to: "provide" },
  {
    id: "equal-equivalence",
    object: "Equal",
    from: "equivalence",
    to: "asEquivalence",
  },
  {
    id: "context-genericTag",
    object: "Context",
    toObject: "ServiceMap",
    from: "GenericTag",
    to: "Service",
  },
  {
    id: "context-make",
    object: "Context",
    toObject: "ServiceMap",
    from: "make",
    to: "make",
  },
  {
    id: "context-get",
    object: "Context",
    toObject: "ServiceMap",
    from: "get",
    to: "get",
  },
  {
    id: "context-add",
    object: "Context",
    toObject: "ServiceMap",
    from: "add",
    to: "add",
  },
  {
    id: "context-mergeAll",
    object: "Context",
    toObject: "ServiceMap",
    from: "mergeAll",
    to: "mergeAll",
  },
  {
    id: "cause-isFailure",
    object: "Cause",
    from: "isFailure",
    to: "hasFails",
  },
  { id: "cause-isDie", object: "Cause", from: "isDie", to: "hasDies" },
  {
    id: "cause-isInterrupted",
    object: "Cause",
    from: "isInterrupted",
    to: "hasInterrupts",
  },
  {
    id: "cause-isInterruptedOnly",
    object: "Cause",
    from: "isInterruptedOnly",
    to: "hasInterruptsOnly",
  },
  {
    id: "cause-isFailType",
    object: "Cause",
    from: "isFailType",
    to: "isFailReason",
  },
  {
    id: "cause-isDieType",
    object: "Cause",
    from: "isDieType",
    to: "isDieReason",
  },
  {
    id: "cause-isInterruptType",
    object: "Cause",
    from: "isInterruptType",
    to: "isInterruptReason",
  },
  {
    id: "cause-sequential",
    object: "Cause",
    from: "sequential",
    to: "combine",
  },
  {
    id: "cause-parallel",
    object: "Cause",
    from: "parallel",
    to: "combine",
  },
  {
    id: "cause-failureOption",
    object: "Cause",
    from: "failureOption",
    to: "findErrorOption",
  },
  {
    id: "cause-failureOrCause",
    object: "Cause",
    from: "failureOrCause",
    to: "findError",
  },
  {
    id: "cause-dieOption",
    object: "Cause",
    from: "dieOption",
    to: "findDefect",
  },
  {
    id: "cause-interruptOption",
    object: "Cause",
    from: "interruptOption",
    to: "findInterrupt",
  },
  {
    id: "cause-noSuchElementException",
    object: "Cause",
    from: "NoSuchElementException",
    to: "NoSuchElementError",
  },
  {
    id: "cause-timeoutException",
    object: "Cause",
    from: "TimeoutException",
    to: "TimeoutError",
  },
  {
    id: "cause-illegalArgumentException",
    object: "Cause",
    from: "IllegalArgumentException",
    to: "IllegalArgumentError",
  },
  {
    id: "cause-exceededCapacityException",
    object: "Cause",
    from: "ExceededCapacityException",
    to: "ExceededCapacityError",
  },
  {
    id: "cause-unknownException",
    object: "Cause",
    from: "UnknownException",
    to: "UnknownError",
  },
  {
    id: "cause-isNoSuchElementException",
    object: "Cause",
    from: "isNoSuchElementException",
    to: "isNoSuchElementError",
  },
  {
    id: "cause-isTimeoutException",
    object: "Cause",
    from: "isTimeoutException",
    to: "isTimeoutError",
  },
  {
    id: "cause-isIllegalArgumentException",
    object: "Cause",
    from: "isIllegalArgumentException",
    to: "isIllegalArgumentError",
  },
  {
    id: "cause-isExceededCapacityException",
    object: "Cause",
    from: "isExceededCapacityException",
    to: "isExceededCapacityError",
  },
  {
    id: "cause-isUnknownException",
    object: "Cause",
    from: "isUnknownException",
    to: "isUnknownError",
  },
  {
    id: "schema-asSchema",
    object: "Schema",
    from: "asSchema",
    to: "revealCodec",
  },
  {
    id: "schema-encodedSchema",
    object: "Schema",
    from: "encodedSchema",
    to: "toEncoded",
  },
  {
    id: "schema-typeSchema",
    object: "Schema",
    from: "typeSchema",
    to: "toType",
  },
  {
    id: "schema-compose",
    object: "Schema",
    from: "compose",
    to: "decodeTo",
  },
  {
    id: "schema-annotations",
    object: "Schema",
    from: "annotations",
    to: "annotate",
  },
  {
    id: "schema-decodeUnknown",
    object: "Schema",
    from: "decodeUnknown",
    to: "decodeUnknownEffect",
  },
  {
    id: "schema-decode",
    object: "Schema",
    from: "decode",
    to: "decodeEffect",
  },
  {
    id: "schema-decodeUnknownEither",
    object: "Schema",
    from: "decodeUnknownEither",
    to: "decodeUnknownResult",
  },
  {
    id: "schema-decodeEither",
    object: "Schema",
    from: "decodeEither",
    to: "decodeResult",
  },
  {
    id: "schema-encodeUnknown",
    object: "Schema",
    from: "encodeUnknown",
    to: "encodeUnknownEffect",
  },
  {
    id: "schema-encode",
    object: "Schema",
    from: "encode",
    to: "encodeEffect",
  },
  {
    id: "schema-encodeUnknownEither",
    object: "Schema",
    from: "encodeUnknownEither",
    to: "encodeUnknownResult",
  },
  {
    id: "schema-encodeEither",
    object: "Schema",
    from: "encodeEither",
    to: "encodeResult",
  },
  {
    id: "schema-bigIntFromSelf",
    object: "Schema",
    from: "BigIntFromSelf",
    to: "BigInt",
  },
  {
    id: "schema-symbolFromSelf",
    object: "Schema",
    from: "SymbolFromSelf",
    to: "Symbol",
  },
  { id: "schema-urlFromSelf", object: "Schema", from: "URLFromSelf", to: "URL" },
  {
    id: "schema-redactedFromSelf",
    object: "Schema",
    from: "RedactedFromSelf",
    to: "Redacted",
  },
  {
    id: "schema-redacted",
    object: "Schema",
    from: "Redacted",
    to: "RedactedFromValue",
  },
  {
    id: "fiberref-currentConcurrency",
    object: "FiberRef",
    toObject: "References",
    from: "currentConcurrency",
    to: "CurrentConcurrency",
  },
  {
    id: "fiberref-currentLogLevel",
    object: "FiberRef",
    toObject: "References",
    from: "currentLogLevel",
    to: "CurrentLogLevel",
  },
  {
    id: "fiberref-currentMinimumLogLevel",
    object: "FiberRef",
    toObject: "References",
    from: "currentMinimumLogLevel",
    to: "MinimumLogLevel",
  },
  {
    id: "fiberref-currentLogAnnotations",
    object: "FiberRef",
    toObject: "References",
    from: "currentLogAnnotations",
    to: "CurrentLogAnnotations",
  },
  {
    id: "fiberref-currentLogSpan",
    object: "FiberRef",
    toObject: "References",
    from: "currentLogSpan",
    to: "CurrentLogSpans",
  },
  {
    id: "fiberref-currentScheduler",
    object: "FiberRef",
    toObject: "References",
    from: "currentScheduler",
    to: "Scheduler",
  },
  {
    id: "fiberref-currentMaxOpsBeforeYield",
    object: "FiberRef",
    toObject: "References",
    from: "currentMaxOpsBeforeYield",
    to: "MaxOpsBeforeYield",
  },
  {
    id: "fiberref-currentTracerEnabled",
    object: "FiberRef",
    toObject: "References",
    from: "currentTracerEnabled",
    to: "TracerEnabled",
  },
  {
    id: "fiberref-unhandledErrorLogLevel",
    object: "FiberRef",
    toObject: "References",
    from: "unhandledErrorLogLevel",
    to: "UnhandledLogLevel",
  },
];
